config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
dbt_asana_uapi:
  outputs:
    prod:
      dbname: customer_6c3a7c66-a5a1-49c9-8149-0aaa3145affd
      host: 3.tcp.eu.ngrok.io
      pass: mutiny
      port: 26688
      schema: public
      threads: 1
      type: postgres
      user: munityapp
  target: prod
