config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
dbt_asana_uapi:
  outputs:
    prod:
      dbname: customer_f5c82a68-7f55-4fe9-aa2a-b3f43c715143
      host: 3.tcp.eu.ngrok.io
      pass: 246f0d6d-b081-4a61-baf5-1b300c27a93c
      port: 26688
      schema: public
      threads: 1
      type: postgres
      user: customer_f5c82a68_7f55_4fe9_aa2a_b3f43c715143
  target: prod
