config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
dbt_asana_uapi:
  outputs:
    prod:
      dbname: customer_92bdc416-a8f4-48a3-9c12-e3bcc418c11d
      host: 3.tcp.eu.ngrok.io
      pass: mutiny
      port: 26688
      schema: public
      threads: 1
      type: postgres
      user: munityapp
  target: prod
